### ISSUE TITLE
Dependency on Python 3.11 is very restrictive.

### ISSUE THREAD

**Issue by imax-erik** [maxharlow/textmatch#1]
Would it be possible to expand the Python dependency to >=3.11, <4.0 (`=^3.11`), or is there a change in Python 3.12 that is known to break this package?

I have a project using Poetry, using Python=^3.11, and I am not able to install this package because it would not be compatible  for Python >= 3.12.

**Comment by maxharlow** [comment]
I'd love to support 3.12 however one of the dependencies -- https://github.com/dedupeio/dedupe -- doesn't yet support it
