### ISSUE TITLE
AttributeError: module 'textmatch' has no attribute 'run'

### ISSUE THREAD

**Issue by theimanph** [maxharlow/textmatch#2]
Hi Max,

I tried to use textmatch with the following code:

import textmatch

data1 = {
        'name': ['William Shakespeare', 'Christopher Marlowe']
    }
data2 = {
        'person': ['Anne Hathaway', 'William Shakespeare']
    }
results = textmatch.run(data1, data2)

And I get this error: AttributeError: module 'textmatch' has no attribute 'run'.. Any ideas? Thank you!!

Sincerely,

tom

**Comment by theimanph** [comment]
I am using python 3.9.18..

**Comment by maxharlow** [comment]
Afraid Textmatch only supports Python 3.11 at the moment https://github.com/maxharlow/textmatch/blob/f730eb7b41a93b558fa1fc53dbf3cda3edbec09b/pyproject.toml#L10

**Comment by theimanph** [comment]
Hi Max, 
Thank you!!!
Sincerely,
tom
